[package]
name = "rust_python"
version = "0.1.0"
edition = "2021"

[dependencies]
pyo3 = { version = "0.18.0", features = ["extension-module"] }

[lib]
name = "rust_python"
crate-type = ["cdylib"]

[profile.release]
opt-level = 3